crmapplication:
  build: .
  command: node server.js
  expose:
    - "3000:3000"
    
nginx:
  restart: always
  build: ./conf/nginx
  links:
      - crmapplication:crmapplication
  ports:
    - "80:80"
